### ISSUE TITLE
Chain Method column does not support nil values

### ISSUE THREAD

**Issue by enriquetuya** [randym/acts_as_xlsx#2]
Hi, I'm having problems when using the gem. My model has an association that accept nulls. This association has a name method, so for the ones that are not null I would like to display the name so I have:

  acts_as_xlsx :columns => [  'supplier.name' ]

Since there are entities that do not have supplier I get:

undefined method `name' for nil:NilClass

Any workarround for this?
Thanks
Enrique

**Comment by randym** [comment]
Hi @enriquetuya

If this is a one off case, I would just put a 'supplier_name' method on your model that basically does:

``` ruby

def supplier_name
  supplier.nil? ? 'foo' : supplier.name
end

```

and use 'supplier_name' in the column spec.

If you have many of these 0..1 relationships, or you are making fairly complex reports, I'd recommend using axlsx directly and authoring data providers in your app so you dont clutter up your models with report context specific methods.

**Comment by enriquetuya** [comment]
Thanks for the answer @randym , I ended up forking up the project and adding the support for nil associations. 
https://github.com/enriquetuya/acts_as_xlsx/commit/71cf6fc47baaf3f7443fc135aaa5bb5c0b251068

Thanks for your anwer.
Regards,
Enrique

**Comment by westonganger** [comment]
@enriquetuya you should make a pull request of this

**Comment by ghost** [comment]
@westonganger I have migrated from act_as_xlsx to [axlsx_rails](https://github.com/straydogstudio/axlsx_rails) it is based on "axls". The true is that when using rails 4.2 I started having too many issues with act_as_xlsx. Hope this helps!

Regards, 
Enrique
