### ISSUE TITLE
Compatibility with Rails 4 / Ruby 2.0

### ISSUE THREAD

**Issue by pisaacs** [randym/acts_as_xlsx#9]
Is your gem compatible with rails 4 / ruby 2.1 and 2.0?

**Comment by straydogstudio** [comment]
@pisaacs At this point it is not compatible with Rails 4.1, since find(:all) has been removed. In the meantime you can use my version here: https://github.com/straydogstudio/acts_as_xlsx

``` ruby
gem 'acts_as_axlsx', git: 'git://github.com/straydogstudio/acts_as_xlsx.git'
```

Hopefully @randym will accept the pull request.

**Comment by pisaacs** [comment]
@straydogstudio thank you!

**Comment by ricardodovalle** [comment]
@straydogstudio :clap:

**Comment by bceppi** [comment]
@straydogstudio Is your gem compatible with rails 5 / ruby 2 ?

**Comment by straydogstudio** [comment]
@bceppi It should be. It is tested within another gem, axlsx_rails, and that works for 5.

**Comment by bceppi** [comment]
@straydogstudio Thank you for your fast answer!
